AllCops:
  TargetRubyVersion: 2.7.1
  Exclude:
    - 'app/channels/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
  NewCops: enable

Style/FrozenStringLiteralComment:
  EnforcedStyle: always_true

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 35
  Exclude:
    - app/controllers/api/v1/orders_controller.rb

Metrics/AbcSize:
  Enabled: true
  Exclude:
    - app/models/payload_builder.rb
